
services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=skystore
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - skystore-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d skystore"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    command: ["postgres", "-c", "logging_collector=on"]

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      - REDIS_ARGS="--appendonly yes"
   # volumes:
     # - redis-data:/data
    networks:
      - skystore-network
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Console port
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-data:/data
    networks:
      - skystore-network
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped

networks:
  skystore-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
  minio-data:
    driver: local
  postgres-data:
    driver: local